---
terraform:
  backend:
    type: local
  providers:
    - hcloud

ansible:
  inventory-file: 'my-inventory'
  playbook-file: myplaybook.yaml
variables:
  hcloud:
    textvar: some text
    intvar: 123
    boolvar: true
  hetznerdns:
    complexvar:
      stringprop: string property
      floatprop: 3.14
  digitalocean:
    listvar:
      - name: item1
        foo: bar-item-1
      - name: item2
        foo: bar-item-2
tags:
  foo: foovalue
  bar: barvalue
