---
template-dir: /home/vlada/work/bitshift/altclouds/hetzner/keycloak-simple
terraform:
  backend:
    type: local
  providers:
    - hcloud
ansible:
  inventory-file: inventory
  playbook-file: keycloak-setup.yaml
